### Provider tester

The aim of this notebook is to test the dataprovider and confirm correct functionality. 

In [1]:
from pydst.DataProvider import DataProvider
import tensorflow as tf
import numpy as np

In [2]:
trainProvider = DataProvider(which_set='train', batch_size = 10, win_val = 1, num_tags = 6)
print(trainProvider.num_batches)

51


In [3]:
sess = tf.Session()

In [4]:
trainProvider.start(sess)

In [5]:
for i in range(1, trainProvider.num_batches):
    [inputs, targets] = trainProvider.request(sess)
    
    if i % 25 == 0:
        print(inputs)
        print('')
        print(targets)
        print i

[[ 435.  435.  435.  435.]
 [ 271.  271.  271.  271.]
 [ 396.  396.  396.  396.]
 [  96.   96.   96.   96.]
 [ 280.  280.  280.  280.]
 [ 399.  399.  399.  399.]
 [  90.   90.   90.   90.]
 [ 135.  135.  135.  135.]
 [ 329.  329.  329.  329.]
 [ 132.  132.  132.  132.]]

[[ 1.  1.  0.  1.  1.  0.]
 [ 1.  0.  0.  0.  0.  1.]
 [ 1.  1.  0.  0.  0.  1.]
 [ 0.  0.  1.  1.  0.  0.]
 [ 1.  0.  0.  0.  1.  1.]
 [ 1.  1.  0.  0.  0.  1.]
 [ 0.  0.  1.  0.  1.  1.]
 [ 0.  1.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  0.  1.]
 [ 0.  1.  0.  0.  0.  0.]]
25
[[ 435.  435.  435.  435.]
 [ 271.  271.  271.  271.]
 [ 396.  396.  396.  396.]
 [  96.   96.   96.   96.]
 [ 280.  280.  280.  280.]
 [ 399.  399.  399.  399.]
 [  90.   90.   90.   90.]
 [ 135.  135.  135.  135.]
 [ 329.  329.  329.  329.]
 [ 132.  132.  132.  132.]]

[[ 1.  1.  0.  1.  1.  0.]
 [ 1.  0.  0.  0.  0.  1.]
 [ 1.  1.  0.  0.  0.  1.]
 [ 0.  0.  1.  1.  0.  0.]
 [ 1.  0.  0.  0.  1.  1.]
 [ 1.  1.  0.  0.  0.  1.]
 [ 0.  0.  1.  0.  1

In [6]:
trainProvider.reset(sess)

INFO:tensorflow:Error reported to Coordinator: <type 'exceptions.RuntimeError'>, Attempted to use a closed Session.


Exception in thread Thread-7:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "pydst/DataProvider.py", line 169, in load_q
    while sess.run(self.q.size()) < self.maxq:
  File "/Users/Rachelle/.virtualenvs/dst/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/Users/Rachelle/.virtualenvs/dst/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 914, in _run
    raise RuntimeError('Attempted to use a closed Session.')
RuntimeError: Attempted to use a closed Session.



In [7]:
for i in range(1, trainProvider.num_batches):
    [inputs, targets] = trainProvider.request(sess)
    
    if i % 25 == 0:
        print(inputs)
        print('')
        print(targets)
        print i

RuntimeError: Attempted to use a closed Session.